# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   ci-cd:
#     runs-on: ubuntu-latest

#     env:
#       IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/app:latest
#       CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
#       AWS_REGION: ${{ secrets.AWS_REGION }}

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: 3.11

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r app_files/src/requirements.txt

#     - name: Run tests
#       run: |
#         pytest app_files/src/test_app.py

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build Docker image
#       run: |
#         docker build -t $IMAGE_NAME ./app_files

#     - name: Push Docker image
#       run: |
#         docker push $IMAGE_NAME

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Update kubeconfig
#       run: |
#         aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

#     - name: Upgrade Helm release
#       run: |
#         helm upgrade --install app ./helm-chart --set image.repository=${{ secrets.DOCKER_USERNAME }}/app,image.tag=latest




name: Full CI/CD with Terraform

on:
  push:
    branches:
      - main

jobs:
  infra-app-pipeline:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

    - name: Docker Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app:latest ./app_files
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/app:latest

    - name: Deploy with Helm
      run: helm upgrade --install app ./helm-chart --set image.repository=${{ secrets.DOCKER_USERNAME }}/app,image.tag=latest
